#if !canImport(ObjectiveC)
import XCTest

extension AEToolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AEToolTests = [
        ("testCore", testCore),
        ("testMy", testMy),
        ("testHelp", testHelp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AEToolTests.__allTests__AEToolTests),
    ]
}
#endif
